apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-helm-quarkus
spec:
  destination:
    namespace: gitops-helm-quarkus
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      parameters:
        - name: build.enabled
          value: "false"
        - name: image.name
          value: quay.io/ablock/gitops-helm-quarkus
    repoURL: https://charts.openshift.io
    chart: redhat-quarkus
    targetRevision: 0.0.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
